export const secrets = {
  WEB_APP_FIREBASE_API_KEY: '',
  WEB_APP_FIREBASE_APP_ID: '',
  WEB_APP_FIREBASE_AUTH_DOMAIN: '',
  WEB_APP_FIREBASE_MEASUREMENT_ID: '',
  WEB_APP_FIREBASE_MESSAGING_SENDER_ID: '',
  WEB_APP_FIREBASE_PROJECT_ID: '',
  WEB_APP_FIREBASE_STORAGE_BUCKET: '',
};
